Adds helm chart and ubi8 based Dockerfile
maildev/maildev pull request #316
Opened 2020-07-28 08:52 UTC by jtudelag

Adds helm chart so Maildev can be deployed in OpenShift/K8s easily.

Additionally adds a [ubi8](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image) base Dockerfile.

Current image does no work for some reason.

2021-01-05 16:00 UTC, splitt3r commented
Great work 👍🏻 sth. like https://github.com/maildev/helm would be great. With the chart being published via GitHub pages. Example: github.com/nextcloud/helm

2021-01-06 15:21 UTC, djfarrelly commented
That's a pretty cool idea @splitt3r! What do you think about the separate repo idea @jtudelag?

2021-01-06 16:28 UTC, splitt3r commented on helm-chart/templates/service-web.yaml
> +    - name: web-{{ .Values.ports.smtp }}-tcp
```suggestion
    - name: web-{{ .Values.ports.web }}-tcp
```

2021-01-06 16:29 UTC, splitt3r commented on helm-chart/templates/service-smtp.yaml
> +      port: 25
```suggestion
      port: {{ .Values.ports.smtp }}
```

2021-01-06 16:31 UTC, splitt3r commented on helm-chart/templates/route-smtp.yaml
> +    name: smtp
```suggestion
    name: smtp-{{ include "maildev.fullname" . }}
```

2021-01-06 16:31 UTC, splitt3r commented on helm-chart/templates/route-smtp.yaml
> +  name: "smtp"
To be consinstent with the other route:

```suggestion
  name: "smtp--{{ include "maildev.fullname" . }}"
```

2021-01-06 16:34 UTC, splitt3r requested changes
Some suggestions

2021-01-06 16:40 UTC, splitt3r commented on helm-chart/values.yaml
> +appName: &name maildev
This vaiable / anchor looks unused. Is there any reason to keep it?

2021-01-06 16:43 UTC, splitt3r commented on helm-chart/templates/cm-auto-relay-rules.yaml
> +  name: maildev-relay-rules
What about the labels here?

2021-01-06 18:23 UTC, jtudelag commented
Hey @djfarrelly , @splitt3r. Sure, It makes sense, lets move this to a separate repo ;). 
Question is, how to you want to do it? Feel free to move it yourselves, as I don't think I have permisions to create a new repo ;)

2021-01-07 12:34 UTC, splitt3r commented
I had a look at it and i think sth. like https://github.com/splitt3r/helm but under the MailDev namespace would be nice. I removed the OpenShift stuff as it does not work with K8s. It uses the latest stable 1.1.0 version of the Docker image.

2021-01-08 16:43 UTC, djfarrelly commented
@jtudelag @splitt3r I just forked @splitt3r's repo with Maildev's org: https://github.com/maildev/helm - I think it loses @jtudelag's contributions, but we could move PRs/changes to there if that works with you all. I could also go the route of an empty repo and you both and contribute from there. Let me know and I'm happy to change configurations or perhaps even just add you both as contributors to that repo. Thanks for your work!!

2021-01-08 18:22 UTC, jtudelag commented
Hey @djfarrelly that's absolutely fine! I don't have much time recently to review the changes and contribute them back, If I can recall correctly, they were mostly related to OpenShift, but I will try to contribute them back again when I have some free time.

In the meantime, I will close this PR, as your repo is more than enough.

Thanks!

2021-01-08 18:22 UTC, closed without merging

2021-01-09 18:48 UTC, splitt3r commented
@djfarrelly i think you still need to activate GitHub Pages for the branch https://github.com/maildev/helm/tree/gh-pages and change the link in the repo description 😁

2021-02-02 14:49 UTC, djfarrelly commented
Sorry for the delay @splitt3r - it' been enabled: https://maildev.github.io/helm/ - should we add documentation to this repo's README to tell people about the Helm chart?

2021-02-02 15:30 UTC, splitt3r commented
Sounds great 👍🏻